version: '2'
services:
  neo3:
    privileged: true
    image: ekino/neo4j-cluster:latest
    hostname: neo3
    environment:
      CLUSTER_NODES: neo1,neo2,neo3,neo4
      SERVER_ID: '3'
    stdin_open: true
    volumes:
    - /var/lib/neo4j-3/data/:/var/lib/neo4j/data/
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_soft: neo4j-neo3-1
  neo2:
    privileged: true
    image: ekino/neo4j-cluster:latest
    hostname: neo2
    environment:
      CLUSTER_NODES: neo1,neo2,neo3,neo4
      SERVER_ID: '2'
    stdin_open: true
    volumes:
    - /var/lib/neo4j-2/data/:/var/lib/neo4j/data/
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_soft: neo4j-neo2-1
  neo1:
    privileged: true
    image: ekino/neo4j-cluster:latest
    hostname: neo1
    environment:
      CLUSTER_NODES: neo1,neo2,neo3,neo4
      SERVER_ID: '1'
    stdin_open: true
    volumes:
    - /var/lib/neo4j-1/data/:/var/lib/neo4j/data/
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_soft: neo4j-neo1-1
  neo4j-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 4001:4001/tcp
    - 4002:4002/tcp
    - 4003:4003/tcp
    - 4004:4004/tcp
    - 4005:4005/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  neo4:
    privileged: true
    image: ekino/neo4j-cluster:latest
    hostname: neo4
    environment:
      CLUSTER_NODES: neo1,neo2,neo3,neo4
      SERVER_ID: '4'
    stdin_open: true
    volumes:
    - /var/lib/neo4j-4/data/:/var/lib/neo4j/data/
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_soft: neo4j-neo4-1
